# Generated by Django 5.0.6 on 2024-06-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('the_date', models.TextField(blank=True, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'episode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sentence_number', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'sentence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('utterance_number', models.IntegerField()),
                ('speaker', models.TextField()),
            ],
            options={
                'db_table': 'utterance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word_number', models.IntegerField()),
                ('text', models.TextField()),
                ('part_of_speech', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word',
                'managed': False,
            },
        ),
    ]
