# Generated by Django 5.0.6 on 2024-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seinfeld", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("metadata", models.JSONField()),
                ("search_term", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
